---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Install rpm-build package
  package:
    name: "{{ item }}"
  with_items: 
    - "{{ rpmbuild_pkg }}"
    - "pcre-devel"
    - "gcc"
    - "openssl-devel"
    - "systemd-devel"
  become: yes
  tags:
    - rpmbuild_pkg

- name: Create the RPM macros file
  template:
    src: rpmmacros.j2
    dest: "{{ rpmbuild_user_home }}/.rpmmacros"
  tags:
    - rpmbuild_config
    - rpmbuild_macros

- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rpmbuild_user_name }}"
  with_items: "{{ rpmbuild_dirs }}"
  tags:
    - rpmbuild_config
    - rpmbuild_dir

- name: "Build Haproxy"
  include_tasks: 'haproxy.yaml'
  when: haproxy_version is defined
