---
galaxy_info:
  author: Yuriy Pavlov
  description: 'Deleting Kubernetes serviceaccounts'
  company:
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - kubernetes
dependencies: []
