---

- name: "Copy roles template"
  template:
    src: 'roles.j2'
    dest: "/tmp/{{ namespace }}-roles.yml"
    mode: '0644'
    validate: "python -c 'import yaml,sys;yaml.safe_load(sys.stdin)' < %s"
  register: roles_file

- name: "Create {{ namespace }} roles"
  shell: |
    /usr/local/bin/kubectl apply -f "/tmp/{{ namespace }}-roles.yml"
  ignore_errors: yes
  run_once: true
  changed_when: false
